replicaCount: 1
service:
  enabled: false
deployment:
  enabled: true
image:
  repository: ${ECR_REGISTRY}/chainlog-logger-prod
  pullPolicy: Always
  tag: prod
serviceAccount:
  create: false
ingress:
  enabled: false
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 0.05
    memory: 64Mi
autoscaling:
  enabled: false
env:
  CHAINLOG_REPO:
    type: kv
    value: "makerdao/chainlog-ui"
  PYTHONUNBUFFERED:
    type: kv
    value: "1"
  GITHUB_TOKEN:
    type: parameterStore
    name: github-token
    parameter_name: /eks/maker-prod/chainlog-logger/github-token
externalSecrets:
  clusterSecretStoreName: maker-prod
livenessProbe:
  exec:
    command:
      - /bin/bash
      - -c
      - ps -ef | grep logger.py | grep -v grep
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3
readinessProbe:
  exec:
    command:
      - /bin/bash
      - -c
      - ps -ef | grep logger.py | grep -v grep
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3
