replicaCount: 0
service:
  enabled: false
deployment:
  enabled: true
image:
  repository: ${ECR_REGISTRY}/chainlog-logger-staging
  pullPolicy: IfNotPresent
  tag: staging
serviceAccount:
  create: false
ingress:
  enabled: false
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
env:
  CHAINLOG_REPO:
    type: kv
    value: "makerdao/chainlog-ui"
  PYTHONUNBUFFERED:
    type: kv
    value: "1"
  GITHUB_TOKEN:
    type: parameterStore
    name: github-token
    parameter_name: /eks/maker-staging/chainlog-logger/github-token
externalSecrets:
  clusterSecretStoreName: maker-staging
livenessProbe:
  exec:
    command:
      - /bin/bash
      - -c
      - ps -ef | grep logger.py | grep -v grep
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3
readinessProbe:
  exec:
    command:
      - /bin/bash
      - -c
      - ps -ef | grep logger.py | grep -v grep
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3
